; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board_build.filesystem = littlefs
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.0
    bblanchon/ArduinoJson @ ^7.0.0
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    ricmoo/QRCode @ ^0.0.1

[platformio]
description = Projeto PUC para etiquetas de gôndolas com interfaceamento via API
